### ISSUE TITLE
Colour change takes place slowly after loading a new solution

### ISSUE THREAD

**Issue by PreetSangha** [Wumpf/VSSolutionColor#1]
Hi there, 

First of all this is a great extension. I really like its premise and very very simple use. Thank you for releasing it.

When you have very large solutions sometimes it can take a long time for the colour to change. I was wondering if it's possible to change the colour before the entire solution has loaded please?

**Comment by Wumpf** [comment]
Thx for all that praise :)
Yeah, I also noticed that issue already. Didn't bother me much so far, but now that somebody is asking I'll have a look, maybe this weekend.

**Comment by Wumpf** [comment]
Was surprisingly hard, but works now :). Uploading update to VS gallery now...

**Comment by PreetSangha** [comment]
Brilliant. Thank you much.
