### ISSUE TITLE
Language version

### ISSUE THREAD

**Issue by Danghor** [Wumpf/VSSolutionColor#12]
What C# version should be used to develop this project? Since the `nameof` operator is not used anywhere, for example, should the project stay on C# 5 or could I refactor some parts using new features in C# 6 and 7?

**Comment by Wumpf** [comment]
It's limited by the .Net framework that can be used for VS extensions. I haven't tried but I assume upgrading would either not work in the first place or break compatibility with older VS versions

**Comment by Danghor** [comment]
The targeted frameworks would stay the same, just the required Visual Studio version would change, since a new compiler is needed. To use C#6 efficiently, one would need VS2015 and for C#7, VS2017. Can the new languages be used for this project? If not and it should stay on C#5, can I change the language version in the project files from 'default' to '5' to prevent accidental changes?
