### ISSUE TITLE
Release 1.5 does not start any more in vs2015

### ISSUE THREAD

**Issue by Domderon** [Wumpf/VSSolutionColor#14]
After the update to 1.5 the extension does not run any more in  VS Professional 2015, Version 14.0.25431.01 Update 3.

Here's the error log:

CreateInstance failed for package [SolutionColorPackage]Source: &apos;mscorlib&apos; Description: Could not load file or assembly &apos;Microsoft.VisualStudio.Shell.15.0, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;System.IO.FileNotFoundException: Could not load file or assembly &apos;Microsoft.VisualStudio.Shell.15.0, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;File name: &apos;Microsoft.VisualStudio.Shell.15.0, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos;&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)&#x000D;&#x000A;   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)&#x000D;&#x000A;   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)&#x000D;&#x000A;&#x000D;&#x000A;WRN: Assembly binding logging is turned OFF.&#x000D;&#x000A;To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.&#x000D;&#x000A;Note: There is some performance penalty associated with assembly bind failure logging.&#x000D;&#x000A;To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;

**Comment by Wumpf** [comment]
@Domderon Sorry I broke it for you! I assumed VS2015 compatibility blindly and did no testing since I no longer have an install of it. I attempted a fix and think it is promising, could you confirm for me that this https://www.dropbox.com/s/hconybmcy1ytffe/SolutionColor.vsix?dl=0 version works?
Thank you!

**Comment by Wumpf** [comment]
Confirmed it working on someone else's computer :)

**Comment by Domderon** [comment]
Thanks for the quick fix! I wasn't able to check earlier due to the Easter holiday, but I can confirm it working now. :)

**Comment by Wumpf** [comment]
No worries! Thanks for confirming :)
