### ISSUE TITLE
Visual Studio 2019 style issues and compability warning

### ISSUE THREAD

**Issue by edwig** [Wumpf/VSSolutionColor#16]
In Visual Studio 2019 the title bar color does not colorize the menu titles. So the title bar looks kind-of clunky.
Alsoo: Visual Studio complains that the plugin will lose compatibility with the new plugin architecture of VS.

**Comment by dekenless** [comment]
...and also the title of the solution; it looks like this:
![solutioncolor](https://user-images.githubusercontent.com/10144906/58495366-50cf4c00-8145-11e9-86a4-3346ab481343.png)

**Comment by Wumpf** [comment]
Huh odd I thought I fixed all those compatibility issues, didn't see any warnings anymore. Gonna have another look.

Regarding the style:
Problem is that if I color the menu as well, the font might get unreadable, so I left it as is.
Someone was raising this on in the reviews on the VS marketplace already as well, so maybe I should reconsider. I guess I could do the same swap between black/white text as I do for the solution title text in older VS versions.

**Comment by edwig** [comment]
As I understand it now: The compatibility warning comes just once, when you install the first time. It says bacscially: "Beware: it won't work in the next version of Visual Studio, so refactor your plugin code". So yea: after just once, you do not see the warning any more.....

**Comment by jasperboot** [comment]
> Regarding the style:
> Problem is that if I color the menu as well, the font might get unreadable, so I left it as is.
> Someone was raising this on in the reviews on the VS marketplace already as well, so maybe I should reconsider. I guess I could do the same swap between black/white text as I do for the solution title text in older VS versions.

I've tried to implement the solution you described here in PR #17.
