### ISSUE TITLE
Color should go when we close solution

### ISSUE THREAD

**Issue by farzadmf** [Wumpf/VSSolutionColor#4]
Hi,

First of all, thank you for this handy solution :)
I think it would be a good idea to remove the color when we close the solution in Visual Studio; otherwise, if we open another solution for which we haven't set a color, both solutions will have the same color.

Thank you

**Comment by Wumpf** [comment]
Oh sure, shouldn't be too hard. :)
Never occurred to me since I tend to close the VS instance and open a new one with a new solution.

**Comment by farzadmf** [comment]
Thanks for the quick solution :)
