### ISSUE TITLE
Does it work on VS 2018? 

### ISSUE THREAD

**Issue by user883311** [Wumpf/VSSolutionColor#6]
Hello -- does the extension work on Macs? 
I have not found it in the VS2018 Extensions (in the application). 
I have not been able to install the .vsix file manually in VS2018. I got the folowing error message: 

`extension/package.json not found inside zip`

**Comment by Wumpf** [comment]
No, this is a Visual Studio extension. "Visual Studio for Mac" is a rebranded version of Xamarin Studio and couldn't be more different :)
