### ISSUE TITLE
Installation failed for VS 2013

### ISSUE THREAD

**Issue by ArjangAssadi** [Wumpf/VSSolutionColor#7]
Installation failed for VS 2013

From installation log file :

18/10/2018 4:28:35 PM - Found installed product - Microsoft Visual Studio Premium 2013
18/10/2018 4:28:35 PM - Found installed product - Microsoft Visual Studio Professional 2013
18/10/2018 4:28:35 PM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)

The tag on 
https://marketplace.visualstudio.com/items?itemName=Wumpf.SolutionColor

says :

Works with
Visual Studio 2012, 2013, 2015, 2017

What am I missing to get it installed for 2013?

Regards

Arjang

**Comment by Wumpf** [comment]
I actually never tried it myself, someone else did and assured me it worked out of the box. I suppose I'll just remove it from the list whenever I update the extension again.

**Comment by Wumpf** [comment]
I'm now officially no longer supporting vs2013 since some new vs extensions apis that were introduced in vs2015 are starting to become mandatory in vs2019
.. also I have no means of testing vs2013
