### ISSUE TITLE
VS2019 Compatibility

### ISSUE THREAD

**Issue by mzhukovs** [Wumpf/VSSolutionColor#8]
With VS2019 in preview, and it appearing to be fairly simple to update extensions to be compatible (i think the loading of it just has to be made async) - wanted to check if this was on your radar? As i love this extension (thank you!) and am already using the preview.

**Comment by yuxiliu** [comment]
The same here, hope the vs2019 support will come soon!

**Comment by mzhukovs** [comment]
VS2019 now out! But it does seem like it's a bit more work as they combined the top bar with the menu bar so probably more stuff to take into account now... 
![image](https://user-images.githubusercontent.com/13161978/55847163-dccbeb00-5b7a-11e9-9a36-f7f2f9ee2865.png)
